Add jacoco to gsheet action
gps/jacoco-to-gsheet pull request #3
Opened 2021-09-27 06:30 UTC by rahul2417

2021-09-27 07:34 UTC, rahul2417 commented on index.js
> +  var isPreviousRecordSame = false;
The CSV report generated by jacoco [link](https://drive.google.com/file/d/1M_lwOW-Y1LTlkEy1SoGX6hoH7eSAER0D/view?usp=sharing) is not in the format that we need. Jacoco generates reports for each function in the code and it is 1400 lines. This function combines the data of the same package to one.

2021-10-04 03:53 UTC, mayurdhaka-suryasoftware requested changes
Can you show me a working of this in the BCN repo?

2021-10-04 03:53 UTC, mayurdhaka-suryasoftware commented on index.js
> +  var refactoredCodeCoverageData = getRefactorCSVCodeCoverageData(codeCoverageData);
```suggestion
  var refactoredCodeCoverageData = getRefactoredCSVCodeCoverageData(codeCoverageData);
```

2021-10-04 03:53 UTC, mayurdhaka-suryasoftware commented on index.js
> +    console.error(e)
Shouldn't you terminate the program? This will silently "make it work". You don't want that. I think just not `catch`ing should do the trick?

2021-10-04 03:56 UTC, rahul2417 commented
>Can you show me a working of this in the BCN repo?

https://docs.google.com/spreadsheets/d/1l2QViepZyw1W3lPXV4rtxBaUx3nhsKdCtMsIjijfIJU/edit#gid=0

2021-10-04 07:06 UTC, mayurdhaka-suryasoftware commented
@rahul2417 access requested.

2021-10-04 07:21 UTC, rahul2417 commented
@mayurdhaka-suryasoftware Access request accepted

2021-10-05 06:03 UTC, mayurdhaka-suryasoftware commented
Google Sheet should update the same column date if I run the action multiple times on the same date.
Please also get @gps to review this.

2021-10-09 13:10 UTC, gps requested changes
@rahul2417 can you please send me an example spreadsheet with this data?

2021-10-09 13:10 UTC, gps commented on .gitignore
> -dist
Reason?

2021-10-09 13:10 UTC, gps commented on README.md
> +- Path pf the code coverage CSV generated by jacoco.
Typo: `pf`

2021-10-09 13:10 UTC, gps commented on README.md
> +  uses: gps/jacoco-to-gsheet@@master
Typo - 2 `@`

2021-10-09 13:10 UTC, gps commented on index.js
> +  const codeCoverageData = fs.readFileSync(path).toString().split('\n').map(e => e.trim()).map(e => e.split(',').map(e => e.trim()));
Please break this up into multiple lines to make it easier to read.

2021-10-09 13:10 UTC, gps commented on index.js
> +  var googleSheetData
Always include `;`. 

Avoid use of `var` whenever possible, prefer `let` or `const`.

2021-10-11 02:46 UTC, rahul2417 commented
>@rahul2417 can you please send me an example spreadsheet with this data?

@gps please check https://docs.google.com/spreadsheets/d/1l2QViepZyw1W3lPXV4rtxBaUx3nhsKdCtMsIjijfIJU/edit#gid=0

2021-10-11 03:09 UTC, rahul2417 commented on .gitignore
> -dist
For this GitHub action https://github.com/gps/jacoco-to-gsheet/blob/master/.github/workflows/build.yml#L7 to run. It generates index.js in the dist folder. If this is not removed from the `gitIgnore` file, the GitHub action fails giving the error `The following path is ignored by gitignore`. So removed it

2021-10-12 03:58 UTC, gps approved these changes

2021-10-12 03:59 UTC, merged